Initial functional package
quant-aq/r-quantaq pull request #1
Opened 2023-08-22 21:00 UTC by christopherDT

The initial functional version of the package, with all main functionality present. To be beta tested while buttoning everything up for CRAN requirements

2023-08-22 21:02 UTC, christopherDT commented
@dhhagan for review when available

2023-08-29 13:34 UTC, dhhagan requested changes
Just a few comments, but otherwise ready to merge!

2023-08-29 13:34 UTC, dhhagan commented on LICENSE.md
Could we switch this to an Apache-2.0 license?

2023-08-29 13:34 UTC, dhhagan commented on tests/testthat/setup.R
Does this mean that CRAN/R don't have a way to keep secrets out of test suites for the purpose of submitting to CRAN? I'm not familiar with the process, but am curious. Or is this something we can store in the github org as a secret and pull via an action to run tests/build/submit to CRAN?

2023-08-29 13:34 UTC, dhhagan commented on R/wrappers.R
> +get_data <- function(sn, limit = NULL, start = NULL, stop = NULL, filter = NULL, sort = NULL, raw = FALSE){
I think we may want to set a non-NULL limit as right now the default behavior is to grab all data for a sensor (I think?) which can easily be millions of records which isn't something we likely want to encourage.

2023-08-29 19:00 UTC, christopherDT commented
@dhhagan -- both the license change and setting a `get_data()` limit default have been handled. Waiting to hear back from CRAN on how to handle the API key issue

2023-08-30 01:45 UTC, dhhagan approved these changes

2023-08-30 01:45 UTC, merged